#ifndef BSWM_CFG_H
#define BSWM_CFG_H

#include "BswM_Types.h"

#define BSWM_DEV_ERROR_DETECT	STD_ON

#define BSWM_VERSIONINFO_API	STD_ON

//#define BSWM_MAINFUNCTION_PERIOD	*

#define BSWM_LOGICAL_EXPRESSION_CNT	2
#define BSWM_MODE_CONDITION_CNT	2
#define BSWM_MODE_REQUEST_PORT_CNT	2
#define BSWM_RULE_CNT	2
#define BSWM_ACTION_CNT 2
#define BSWM_ACTION_LIST_CNT 2

#endif
